<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'XFGW' => 1,
        'XWXCB' => 2,
        'XWMB' => 3,
        'RHLHXZH' => 4,
        'XWZFW' => 5,
        'XRMFY' => 6,
        'XJCY' => 7,
        'XGAJ' => 8,
        'XCZJ' => 9,
        'XGXW' => 10,
        'XGZW' => 11,
        'XJYJ' => 12,
        'XSFJ' => 13,
        'XRSJ' => 14,
        'XZJJ' => 15,
        'XGSL' => 16,
        'XGBDST' => 17,
        'XSWJ' => 18,
        'XLYJ' => 19,
        'XJTYSJ' => 20,
        'XLFW' => 21,
        'XFGJ' => 22,
        'XSTHJJ' => 23,
        'XSWUJ' => 24,
        'XMZJ' => 25,
        'XNYJ' => 26,
        'XWGXJ' => 27,
        'XGTZYJ' => 28,
        'XWJW' => 29,
        'XGSJ' => 30,
        'XDSJ' => 31,
        'XTJJ' => 32,
        'XSCHZLJGJ' => 33,
        'XAJJ' => 34,
        'XZFFZB' => 35,
        'XZFJRB' => 36,
        'XGGZWGLJ' => 37,
        'XXXZX' => 38,
        'XWWXB' => 39,
        'XBWB' => 40,
        'XKJJ' => 41,
        'XSJJ' => 42,
        'XLSJ' => 43,
        'XGHJ' => 44,
        'XCGZFJ' => 45,
        'XDAJ' => 46,
        'XZGH' => 47,
        'TXW' => 48,
        'XQXJ' => 49,
        'XGDGS' => 50,
        'XDXGS' => 51,
        'XYDGS' => 52,
        'XLTGS' => 53,
        'XRQYXGS' => 54,
        'XCXJSCJH' => 55,
    );
}
