<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'JMKJFGJ' => 1,
        'DZBGS' => 2,
        'DQGZB' => 3,
        'JGDGW' => 4,
        'RDZXLLC' => 5,
        'JGW' => 6,
        'ZSJ' => 7,
        'CZJ' => 8,
        'GZW' => 9,
        'JSJ' => 10,
        'SHFZJ' => 11,
        'JYTYJ' => 12,
        'CSGLJ' => 13,
        'GXFT' => 14,
        'WZBZFB' => 15,
        'SQGLJ' => 16,
        'MSJ' => 17,
        'GGZWGLJ' => 18,
        'WJW' => 19,
        'XFJ' => 20,
        'HBJ' => 21,
        'YLGLJ' => 22,
        'CHY' => 23,
        'ZAXFDD' => 24,
        'ZGH' => 25,
        'YJJXB' => 26,
        'SWYYB' => 27,
        'XNYXCLB' => 28,
        'GTB' => 29,
        'ZRZYHGHJ' => 30,
        'GAFJ' => 31,
        'SWJ' => 32,
        'SCJDGLJ' => 33,
        'LYFJ' => 34,
        'SLGAFJ' => 35,
        'JJDD' => 36,
        'JCS' => 37,
        'XFJYDD' => 38,
    );
}
