<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['XFGW'] => 'XFGW',
        IUserGroup::ID['XWXCB'] => 'XWXCB',
        IUserGroup::ID['XWMB'] => 'XWMB',
        IUserGroup::ID['RHLHXZH'] => 'RHLHXZH',
        IUserGroup::ID['XWZFW'] => 'XWZFW',
        IUserGroup::ID['XRMFY'] => 'XRMFY',
        IUserGroup::ID['XJCY'] => 'XJCY',
        IUserGroup::ID['XGAJ'] => 'XGAJ',
        IUserGroup::ID['XCZJ'] => 'XCZJ',
        IUserGroup::ID['XGXW'] => 'XGXW',
        IUserGroup::ID['XGZW'] => 'XGZW',
        IUserGroup::ID['XJYJ'] => 'XJYJ',
        IUserGroup::ID['XSFJ'] => 'XSFJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['XZJJ'] => 'XZJJ',
        IUserGroup::ID['XGSL'] => 'XGSL',
        IUserGroup::ID['XGBDST'] => 'XGBDST',
        IUserGroup::ID['XSWJ'] => 'XSWJ',
        IUserGroup::ID['XLYJ'] => 'XLYJ',
        IUserGroup::ID['XJTYSJ'] => 'XJTYSJ',
        IUserGroup::ID['XLFW'] => 'XLFW',
        IUserGroup::ID['XFGJ'] => 'XFGJ',
        IUserGroup::ID['XSTHJJ'] => 'XSTHJJ',
        IUserGroup::ID['XSWJ'] => 'XSWJ',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['XNYJ'] => 'XNYJ',
        IUserGroup::ID['XWGXJ'] => 'XWGXJ',
        IUserGroup::ID['XGTZYJ'] => 'XGTZYJ',
        IUserGroup::ID['XWJW'] => 'XWJW',
        IUserGroup::ID['XGSJ'] => 'XGSJ',
        IUserGroup::ID['XDSJ'] => 'XDSJ',
        IUserGroup::ID['XTJJ'] => 'XTJJ',
        IUserGroup::ID['XSCHZLJGJ'] => 'XSCHZLJGJ',
        IUserGroup::ID['XAJJ'] => 'XAJJ',
        IUserGroup::ID['XZFFZB'] => 'XZFFZB',
        IUserGroup::ID['XZFJRB'] => 'XZFJRB',
        IUserGroup::ID['XGGZWGLJ'] => 'XGGZWGLJ',
        IUserGroup::ID['XXXZX'] => 'XXXZX',
        IUserGroup::ID['XWWXB'] => 'XWWXB',
        IUserGroup::ID['XBWB'] => 'XBWB',
        IUserGroup::ID['XKJJ'] => 'XKJJ',
        IUserGroup::ID['XSJJ'] => 'XSJJ',
        IUserGroup::ID['XLSJ'] => 'XLSJ',
        IUserGroup::ID['XGHJ'] => 'XGHJ',
        IUserGroup::ID['XCGZFJ'] => 'XCGZFJ',
        IUserGroup::ID['XDAJ'] => 'XDAJ',
        IUserGroup::ID['XZGH'] => 'XZGH',
        IUserGroup::ID['TXW'] => 'TXW',
        IUserGroup::ID['XQXJ'] => 'XQXJ',
        IUserGroup::ID['XGDGS'] => 'XGDGS',
        IUserGroup::ID['XDXGS'] => 'XDXGS',
        IUserGroup::ID['XYDGS'] => 'XYDGS',
        IUserGroup::ID['XLTGS'] => 'XLTGS',
        IUserGroup::ID['XRQYXGS'] => 'XRQYXGS',
        IUserGroup::ID['XCXJSCJH'] => 'XCXJSCJH',
    );
}
