<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['JMKJFGJ'] => 'JMKJFGJ',
        IUserGroup::ID['DZBGS'] => 'DZBGS',
        IUserGroup::ID['DQGZB'] => 'DQGZB',
        IUserGroup::ID['JGDGW'] => 'JGDGW',
        IUserGroup::ID['RDZXLLC'] => 'RDZXLLC',
        IUserGroup::ID['JGW'] => 'JGW',
        IUserGroup::ID['ZSJ'] => 'ZSJ',
        IUserGroup::ID['CZJ'] => 'CZJ',
        IUserGroup::ID['GZW'] => 'GZW',
        IUserGroup::ID['JSJ'] => 'JSJ',
        IUserGroup::ID['SHFZJ'] => 'SHFZJ',
        IUserGroup::ID['JYTYJ'] => 'JYTYJ',
        IUserGroup::ID['CSGLJ'] => 'CSGLJ',
        IUserGroup::ID['GXFT'] => 'GXFT',
        IUserGroup::ID['WZBZFB'] => 'WZBZFB',
        IUserGroup::ID['SQGLJ'] => 'SQGLJ',
        IUserGroup::ID['MSJ'] => 'MSJ',
        IUserGroup::ID['GGZWGLJ'] => 'GGZWGLJ',
        IUserGroup::ID['WJW'] => 'WJW',
        IUserGroup::ID['XFJ'] => 'XFJ',
        IUserGroup::ID['HBJ'] => 'HBJ',
        IUserGroup::ID['YLGLJ'] => 'YLGLJ',
        IUserGroup::ID['CHY'] => 'CHY',
        IUserGroup::ID['ZAXFDD'] => 'ZAXFDD',
        IUserGroup::ID['ZGH'] => 'ZGH',
        IUserGroup::ID['YJJXB'] => 'YJJXB',
        IUserGroup::ID['SWYYB'] => 'SWYYB',
        IUserGroup::ID['XNYXCLB'] => 'XNYXCLB',
        IUserGroup::ID['GTB'] => 'GTB',
        IUserGroup::ID['ZRZYHGHJ'] => 'ZRZYHGHJ',
        IUserGroup::ID['GAFJ'] => 'GAFJ',
        IUserGroup::ID['SWJ'] => 'SWJ',
        IUserGroup::ID['SCJDGLJ'] => 'SCJDGLJ',
        IUserGroup::ID['LYFJ'] => 'LYFJ',
        IUserGroup::ID['SLGAFJ'] => 'SLGAFJ',
        IUserGroup::ID['JJDD'] => 'JJDD',
        IUserGroup::ID['JCS'] => 'JCS',
        IUserGroup::ID['XFJYDD'] => 'XFJYDD',
    );
}
